"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:55:37.054576+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType
import logging
import json
import os

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def validate_columns(df, expected_columns, dataset_name):
    missing_columns = [column_name for column_name in expected_columns if column_name not in df.columns]
    if missing_columns:
        raise ValueError(f"{dataset_name} is missing expected columns: {', '.join(missing_columns)}")

def log_row_count(stage_name, df):
    row_count = df.count()
    logger.info("%s row count: %s", stage_name, row_count)
    return row_count

def ingest_bronze(spark, transactions_input_path, merchants_input_path, transactions_output_path, merchants_output_path, transactions_source_file, merchants_source_file, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.format("csv")
                      .option("header", "true")
                       .option("inferSchema", "false")
                       .load(transactions_input_path)
                      .withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit(transactions_source_file))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    merchants_df = (spark.read.format("csv")
                   .option("header", "true")
                   .option("inferSchema", "false")
                   .load(merchants_input_path)
                   .withColumn("ingestion_timestamp", lit(run_date))
                   .withColumn("source_file", lit(merchants_source_file))
                   .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write both dataframes to Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(transactions_output_path)
    merchants_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(merchants_output_path)
    log_row_count("bronze_transactions", transactions_df)
    log_row_count("bronze_merchants", merchants_df)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.format("parquet")
                       .load(bronze_path)
                      .where(col("ingestion_timestamp") == run_date))
    
    merchants_df = (spark.read.format("parquet")
                   .load(merchants_path)
                   .where(col("ingestion_timestamp") == run_date)
                   .cache())  # Cache the small merchants dataframe

    validate_columns(
        transactions_df,
        ["transaction_id", "merchant_id", "amount", "transaction_date", "ingestion_timestamp"],
        "transactions bronze dataset",
    )
    validate_columns(
        merchants_df,
        ["merchant_id"],
        "merchants bronze dataset",
    )
    
    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(FloatType()))
    transactions_df = transactions_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    transactions_df = transactions_df.withColumn("transaction_id", col("transaction_id").cast(StringType()))
    transactions_df = transactions_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    
    # Filter: remove records where primary and critical columns are NULL or amount < 0
    transactions_df = transactions_df.filter(
        col("transaction_id").isNotNull()
        & col("merchant_id").isNotNull()
        & col("amount").isNotNull()
        & col("transaction_date").isNotNull()
        & (col("amount") >= 0)
    )
    
    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    transactions_dedup_df = (transactions_df.groupBy("transaction_id")
                            .agg({"ingestion_timestamp": "max"})
                            .withColumnRenamed("max(ingestion_timestamp)", "ingestion_timestamp"))
    
    # Join with merchants (broadcast hint, cache merchants)
    transactions_enriched_df = (transactions_df.join(broadcast(merchants_df), transactions_df.merchant_id == merchants_df.merchant_id, "left_outer")
                                .withColumn("quality_flag", 
                                            when(col("merchant_id").isNull(), "UNMATCHED")
                                           .otherwise("CLEAN")))
    
    # Write Silver Parquet partitioned by date
    transactions_enriched_df.write.mode("overwrite").partitionBy("transaction_date").parquet(output_path)
    log_row_count("silver_transactions", transactions_enriched_df)

def main():
    # Initialize SparkSession
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    transactions_input_path = os.getenv("TRANSACTIONS_INPUT_PATH")
    merchants_input_path = os.getenv("MERCHANTS_INPUT_PATH")
    transactions_source_file = os.getenv("TRANSACTIONS_SOURCE_FILE")
    merchants_source_file = os.getenv("MERCHANTS_SOURCE_FILE")
    bronze_transactions_path = os.getenv("BRONZE_TRANSACTIONS_PATH")
    bronze_merchants_path = os.getenv("BRONZE_MERCHANTS_PATH")
    silver_path = os.getenv("SILVER_OUTPUT_PATH")
    merchant_performance_path = os.getenv("GOLD_MERCHANT_PERFORMANCE_PATH")
    customer_ltv_path = os.getenv("GOLD_CUSTOMER_LTV_PATH")
    daily_summary_path = os.getenv("GOLD_DAILY_SUMMARY_PATH")
    run_date = os.getenv("RUN_date")
    run_id = os.getenv("RUN_ID")
    metadata_output_path = os.getenv("METADATA_OUTPUT_PATH")
    
    # Ingest Bronze
    try:
        ingest_bronze(
            spark,
            transactions_input_path,
            merchants_input_path,
            bronze_transactions_path,
            bronze_merchants_path,
            transactions_source_file,
            merchants_source_file,
            run_date,
            run_id,
        )
    except Exception as exc:
        print(f"Bronze ingestion failed: {exc}")
        raise
    
    # Transform Silver
    try:
        transform_silver(spark, bronze_transactions_path, bronze_merchants_path, silver_path, run_date)
    except Exception as exc:
        print(f"Silver transformation failed: {exc}")
        raise
    
    # Write run metadata summary to a JSON file
    run_metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    try:
        if not metadata_output_path:
            raise ValueError("METADATA_OUTPUT_PATH is required")
        with open(metadata_output_path, "w") as f:
            json.dump(run_metadata, f)
    except Exception as exc:
        print(f"Metadata write failed: {exc}")
        raise

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, coalesce, mode, to_date, lit
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def run_gold(spark, silver_path, merchant_performance_path, customer_ltv_path, daily_summary_path, metadata_output_path, run_date):
    # Initialize metadata dictionary
    run_metadata = {}

    # Build Gold tables
    try:
        build_merchant_performance(spark, silver_path, merchant_performance_path, run_date)
        build_customer_ltv(spark, silver_path, customer_ltv_path)
        build_daily_summary(spark, silver_path, daily_summary_path, run_date)
    except Exception as exc:
        print(f"Gold pipeline failed: {exc}")
        raise

    # Write run metadata to JSON
    try:
        if not metadata_output_path:
            raise ValueError("METADATA_OUTPUT_PATH is required")
        spark.sparkContext.parallelize([run_metadata]).write.json(metadata_output_path)
    except Exception as exc:
        print(f"Gold metadata write failed: {exc}")
        raise

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("date") == run_date)
    validate_columns(
        silver_df,
        ["merchant_id", "merchant_name", "category", "city", "date", "amount", "status"],
        "silver dataset for merchant performance",
    )

    # Calculate metrics
    merchant_performance_df = (
        silver_df.filter(col("status") == "COMPLETED")
       .groupBy("merchant_id", "merchant_name", "category", "city", "date")
        .agg(
            sum(col("amount")).alias("total_revenue"),
            count("*").alias("txn_count"),
            count(when(col("status") == "FAILED", 1)).alias("failed_txns"),
            count("*").alias("total_txns")
        )
        .withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast("float"))
        .drop("failed_txns")
    )

    # Write output
    merchant_performance_df.repartition("date").write.mode("overwrite").parquet(output_path)
    log_row_count("gold_merchant_performance", merchant_performance_df)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    validate_columns(
        silver_df,
        ["customer_id", "amount", "transaction_date", "payment_method", "status"],
        "silver dataset for customer LTV",
    )
    silver_df = silver_df.filter(col("status") == "COMPLETED")

    # Calculate metrics
    customer_ltv_df = (
        silver_df.groupBy("customer_id")
        .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            mode("payment_method").over(Window.partitionBy("customer_id")).alias("preferred_payment_method")
        )
    )

    # Write output
    customer_ltv_df.write.mode("overwrite").parquet(output_path)
    log_row_count("gold_customer_ltv", customer_ltv_df)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("date") == run_date)
    validate_columns(
        silver_df,
        ["date", "amount", "customer_id", "merchant_id", "status"],
        "silver dataset for daily summary",
    )

    # Calculate metrics
    daily_summary_df = (
        silver_df.groupBy("date")
       .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id").distinct()).alias("unique_customers"),
            count(col("merchant_id").distinct()).alias("unique_merchants"),
            count(when(col("status") == "FAILED", 1)).alias("failed_txns"),
            count("*").alias("total_txns")
        )
       .withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast("float"))
       .drop("failed_txns")
    )

    # Write output
    daily_summary_df.repartition("date").write.mode("overwrite").parquet(output_path)
    log_row_count("gold_daily_summary", daily_summary_df)

# Initialize Spark session
spark = (SparkSession.builder
         .appName("Sigma DataTech Transaction Analytics Pipeline")
         .getOrCreate())
