"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:53:33.491261+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType
import json

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.format("csv")
                       .option("header", "true")
                        .option("inferSchema", "false")
                        .load(input_path)
                       .withColumnRenamed("_c0", "transaction_id")
                       .withColumnRenamed("_c1", "merchant_id")
                       .withColumnRenamed("_c2", "amount")
                       .withColumnRenamed("_c3", "transaction_date")
                       .withColumnRenamed("_c4", "status")
                       .withColumn("ingestion_timestamp", lit(run_date))
                       .withColumn("source_file", lit(input_path))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.partitionBy("transaction_date").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.format("parquet")
                       .load(bronze_path)
                      .where(col("transaction_date") == run_date))
    
    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(FloatType()))
    transactions_df = transactions_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    transactions_df = transactions_df.withColumn("transaction_id", col("transaction_id").cast(StringType()))
    transactions_df = transactions_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    
    # Filter NULL transaction_id and negative amounts
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Read merchants data and cache it
    merchants_df = (spark.read.format("csv")
                   .option("header", "true")
                   .option("inferSchema", "false")
                   .load(merchants_path)
                   .withColumnRenamed("_c0", "merchant_id")
                   .withColumnRenamed("_c1", "merchant_name")
                   .withColumnRenamed("_c2", "category")
                   .withColumnRenamed("_c3", "city")
                   .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    merchants_df = merchants_df.cache()
    
    # Deduplicate on transaction_id keeping the latest ingestion_timestamp
    transactions_df = (transactions_df.withColumn("row_number", 
                                                   when(col("transaction_id").isNotNull(), 
                                                        col("transaction_id").cast("long")).otherwise(0))
                      .withColumn("row_number", 
                                  col("row_number") + col("ingestion_timestamp").cast("long")))
    deduped_transactions_df = transactions_df.groupBy("transaction_id").agg({"row_number": "max"}).alias("max_row_number")
    transactions_df = transactions_df.join(deduped_transactions_df, "transaction_id").join(deduped_transactions_df, "max_row_number")
    transactions_df = transactions_df.drop("row_number", "max_row_number")
    
    # Join with merchants (broadcast hint, cache merchants)
    transactions_df = transactions_df.join(broadcast(merchants_df), "merchant_id", "left_outer")
    
    # Add quality_flag column (CLEAN or UNMATCHED)
    transactions_df = transactions_df.withColumn("quality_flag", 
                                                 when(col("merchant_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    
    # Write as Parquet partitioned by date
    transactions_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize SparkSession
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://sigma-datatech/raw/transactions.csv"
    merchants_path = "s3://sigma-datatech/raw/merchants.csv"
    bronze_path = "s3://sigma-datatech/bronze/transactions"
    silver_path = "s3://sigma-datatech/silver/transactions"
    run_date = "2026-05-27"
    run_id = "run_id_20260527"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, bronze_path, merchants_path, silver_path, run_date)
    
    # Log run metadata summary to a JSON file
    run_metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(f"s3://sigma-datatech/metadata/run_metadata_{run_date}.json", "w") as f:
        json.dump(run_metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, coalesce, mode, to_date, lit
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType, IntegerType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Initialize run metadata
    run_metadata = {
        "run_date": run_date,
        "status": "COMPLETED",
        "tables": []
    }

    # Build Gold tables
    build_merchant_performance(spark, f"{silver_path}/date={run_date}", f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, f"{silver_path}", f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, f"{silver_path}/date={run_date}", f"{gold_output_dir}/daily_summary", run_date)

    # Write run metadata to JSON
    run_metadata_df = spark.createDataFrame([(run_metadata,)], ["metadata"])
    run_metadata_df.write.json(f"{gold_output_dir}/run_metadata")

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data for the specified date
    silver_df = spark.read.parquet(silver_path)

    # Filter for completed transactions and calculate metrics
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    revenue_df = completed_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(sum("amount").alias("total_revenue"), count("*").alias("txn_count"))

    # Calculate failure rate
    all_txns_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(count("*").alias("total_txns"), count(when(col("status") == "FAILED", 1)).alias("failed_txns"))
    failure_rate_df = all_txns_df.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))

    # Join revenue and failure rate metrics
    merchant_performance_df = revenue_df.join(failure_rate_df, ["merchant_id", "merchant_name", "category", "city", "date"], "left") \
        .select("merchant_id", "merchant_name", "category", "city", "date", "total_revenue", "txn_count", "failure_rate_pct")

    # Write the output to Gold layer
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)

    # Filter for completed transactions and calculate metrics
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    ltv_df = completed_df.groupBy("customer_id") \
       .agg(sum("amount").alias("total_spent"), count("*").alias("total_txns"), 
            avg("amount").alias("avg_txn_value"), 
            min("transaction_date").alias("first_txn_date"), 
            max("transaction_date").alias("last_txn_date"))

    # Determine preferred payment method (mode)
    payments_df = silver_df.groupBy("customer_id", "payment_method").agg(count("*").alias("payment_count"))
    max_payments_df = payments_df.groupBy("customer_id").agg(max("payment_count").alias("max_count"))
    preferred_payments_df = payments_df.join(max_payments_df, ["customer_id", "max_count"]).select("customer_id", "payment_method")
    preferred_payments_agg_df = preferred_payments_df.groupBy("customer_id").agg(mode("payment_method").alias("preferred_payment_method"))

    # Join LTV metrics with preferred payment method
    customer_ltv_df = ltv_df.join(preferred_payments_agg_df, "customer_id", "left") \
       .select("customer_id", "total_spent", "total_txns", "avg_txn_value", "first_txn_date", "last_txn_date", "preferred_payment_method")

    # Write the output to Gold layer
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data for the specified date
    silver_df = spark.read.parquet(silver_path)

    # Calculate total revenue, total transactions, unique customers, and unique merchants
    revenue_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("date").agg(sum("amount").alias("total_revenue"), count("*").alias("total_txns"))

    unique_customers_df = silver_df.groupBy("date", "customer_id").agg(max("transaction_date").alias("last_txn_date")) \
       .groupBy("date").agg(countDistinct("customer_id").alias("unique_customers"))

    unique_merchants_df = silver_df.groupBy("date", "merchant_id").agg(max("transaction_date").alias("last_txn_date")) \
       .groupBy("date").agg(countDistinct("merchant_id").alias("unique_merchants"))

    # Calculate failure rate
    all_txns_df = silver_df.groupBy("date").agg(count("*").alias("total_txns"), count(when(col("status") == "FAILED", 1)).alias("failed_txns"))
    failure_rate_df = all_txns_df.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))

    # Join all metrics
    daily_summary_df = revenue_df.join(unique_customers_df, "date", "inner") \
        .join(unique_merchants_df, "date", "inner") \
       .join(failure_rate_df, "date", "left") \
       .select("date", "total_revenue", "total_txns", "unique_customers", "unique_merchants", "failure_rate_pct")

    # Write the output to Gold layer
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path)
